### ISSUE TITLE
my xinput --list gets the device two times

### ISSUE THREAD

**Issue by aligator** [pbnelson/rotswap#3]
A little error with the new script on my device:

$ xinput --list
⎡ Virtual core pointer                    	id=2	[master pointer  (3)]
⎜   ↳ Virtual core XTEST pointer              	id=4	[slave  pointer  (2)]
⎜   ↳ SYNA7508:00 06CB:10EB Pen               	id=9	[slave  pointer  (2)]
⎜   ↳ SYNA7508:00 06CB:10EB                   	id=10	[slave  pointer  (2)]
⎜   ↳ ITE Tech. Inc. ITE Device(8595)         	id=7	[slave  pointer  (2)]
⎜   ↳ ITE Tech. Inc. ITE Device(8595) Touchpad	id=8	[slave  pointer  (2)]
⎣ Virtual core keyboard                   	id=3	[master keyboard (2)]
    ↳ Virtual core XTEST keyboard             	id=5	[slave  keyboard (3)]
    ↳ Video Bus                               	id=6	[slave  keyboard (3)]
    ↳ gpio-keys                               	id=11	[slave  keyboard (3)]
    ↳ gpio-keys                               	id=12	[slave  keyboard (3)]
    ↳ Acer WMI hotkeys                        	id=13	[slave  keyboard (3)]

so your script gets
$ xinput --list|egrep -o "SYNA\w{4}:\w{2} \w{4}:\w{4}"
SYNA7508:00 06CB:10EB
SYNA7508:00 06CB:10EB

a simple
| head -n1
should fix this

**Comment by pbnelson** [comment]
Fix is in!
